# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datastore', '0028_auto_20160721_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionMembership',
            fields=[
                ('registry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Connection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Project')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='projects',
            field=models.ManyToManyField(through='registry.ConnectionMembership', to='datastore.Project'),
        ),
    ]
