# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0021_auto_20160331_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeterResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[(b'RESIDENTIAL', b'Residential'), (b'COMMERICAL', b'Commercial')], max_length=250, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('n_days', models.IntegerField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Project')),
            ],
        ),
        migrations.AddField(
            model_name='projectmeterresult',
            name='project_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectRun'),
        ),
        migrations.AddField(
            model_name='meterrun',
            name='project_meter_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectMeterResult'),
        ),
    ]
