# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0021_auto_20160331_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRunJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'submitted'), (2, b'running'), (3, b'success'), (4, b'failure')], default=1)),
                ('status_text', models.TextField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Project')),
            ],
        ),
    ]
