# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0022_projectrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrun',
            name='meter_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERICAL', 'Commercial')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=250),
        ),
    ]
