# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0022_projectrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrun',
            name='traceback',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='projectrun',
            name='meter_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='RESIDENTIAL', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=250),
        ),
    ]
