# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('datastore', '0022_auto_20160505_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrun',
            name='task_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.TaskMeta'),
        ),
    ]
