# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0023_projectrun_meter_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrun',
            name='meter_type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
