# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0024_auto_20160525_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumptionmetadata',
            old_name='energy_unit',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='projectrun',
            name='meter_class',
            field=models.CharField(default='EnergyEfficiencyMeter', max_length=250, null=True),
        ),
    ]
