# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 22:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0024_auto_20160525_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterrun',
            name='meter_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
