# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0024_auto_20160525_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrun',
            name='meter_type',
            field=models.CharField(default=b'DefaultResidentialMeter', max_length=250, null=True),
        ),
    ]
