# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 19:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0025_auto_20160712_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DerivativeAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_interpretation', models.CharField(max_length=100)),
                ('interpretation', models.CharField(max_length=100)),
                ('baseline_value', models.FloatField()),
                ('baseline_upper', models.FloatField()),
                ('baseline_lower', models.FloatField()),
                ('baseline_n', models.IntegerField()),
                ('reporting_value', models.FloatField()),
                ('reporting_upper', models.FloatField()),
                ('reporting_lower', models.FloatField()),
                ('reporting_n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyTraceModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('cvrmse', models.FloatField(blank=True, null=True)),
                ('model_serializiation', models.CharField(blank=True, max_length=10000, null=True)),
                ('upper', models.FloatField(blank=True, null=True)),
                ('lower', models.FloatField(blank=True, null=True)),
                ('n', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.CharField(choices=[('BASELINE', 'Baseline'), ('REPORTING', 'Reporting')], max_length=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelingPeriodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_period', to='datastore.ModelingPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eemeter_version', models.CharField(max_length=100)),
                ('meter_class', models.CharField(blank=True, max_length=250, null=True)),
                ('meter_settings', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyusagebaseline',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='dailyusagereporting',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummaryactual',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummarybaseline',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummaryreporting',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='fueltypesummary',
            name='project_block',
        ),
        migrations.RemoveField(
            model_name='meterrun',
            name='consumption_metadata',
        ),
        migrations.RemoveField(
            model_name='meterrun',
            name='project',
        ),
        migrations.RemoveField(
            model_name='monthlyaverageusagebaseline',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='monthlyaverageusagereporting',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummaryactual',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummarybaseline',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummaryreporting',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='consumptionmetadata',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='projectrun',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectrun',
            name='n_days',
        ),
        migrations.RemoveField(
            model_name='projectrun',
            name='start_date',
        ),
        migrations.AddField(
            model_name='consumptionmetadata',
            name='interpretation',
            field=models.CharField(choices=[('E_C_S', 'ELECTRICITY_CONSUMPTION_SUPPLIED'), ('E_C_T', 'ELECTRICITY_CONSUMPTION_TOTAL'), ('E_C_N', 'ELECTRICITY_CONSUMPTION_NET'), ('E_OSG_T', 'ELECTRICITY_ON_SITE_GENERATION_TOTAL'), ('E_OSG_C', 'ELECTRICITY_ON_SITE_GENERATION_CONSUMED'), ('E_OSG_U', 'ELECTRICITY_ON_SITE_GENERATION_UNCONSUMED'), ('NG_C_S', 'NATURAL_GAS_CONSUMPTION_SUPPLIED')], default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumptionmetadata',
            name='label',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.DeleteModel(
            name='DailyUsageBaseline',
        ),
        migrations.DeleteModel(
            name='DailyUsageReporting',
        ),
        migrations.DeleteModel(
            name='DailyUsageSummaryActual',
        ),
        migrations.DeleteModel(
            name='DailyUsageSummaryBaseline',
        ),
        migrations.DeleteModel(
            name='DailyUsageSummaryReporting',
        ),
        migrations.DeleteModel(
            name='FuelTypeSummary',
        ),
        migrations.DeleteModel(
            name='MeterRun',
        ),
        migrations.DeleteModel(
            name='MonthlyAverageUsageBaseline',
        ),
        migrations.DeleteModel(
            name='MonthlyAverageUsageReporting',
        ),
        migrations.DeleteModel(
            name='MonthlyUsageSummaryActual',
        ),
        migrations.DeleteModel(
            name='MonthlyUsageSummaryBaseline',
        ),
        migrations.DeleteModel(
            name='MonthlyUsageSummaryReporting',
        ),
        migrations.AddField(
            model_name='modelingperiodgroup',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='modelingperiodgroup',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_period', to='datastore.ModelingPeriod'),
        ),
        migrations.AddField(
            model_name='modelingperiod',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='energy_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ConsumptionMetadata'),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='modeling_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ModelingPeriod'),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='derivativeaggregation',
            name='modeling_period_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ModelingPeriodGroup'),
        ),
        migrations.AddField(
            model_name='derivativeaggregation',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='derivative',
            name='energy_trace_model_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.EnergyTraceModelResult'),
        ),
    ]
