# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0025_auto_20160525_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrun',
            old_name='meter_type',
            new_name='meter_class',
        ),
        migrations.RemoveField(
            model_name='meterrun',
            name='meter_type',
        ),
        migrations.AddField(
            model_name='meterrun',
            name='meter_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
