# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0025_auto_20160712_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.CharField(choices=[('E_C_S', 'ELECTRICITY_CONSUMPTION_SUPPLIED'), ('E_C_T', 'ELECTRICITY_CONSUMPTION_TOTAL'), ('E_C_N', 'ELECTRICITY_CONSUMPTION_NET'), ('E_OSG_T', 'ELECTRICITY_ON_SITE_GENERATION_TOTAL'), ('E_OSG_C', 'ELECTRICITY_ON_SITE_GENERATION_CONSUMED'), ('E_OSG_U', 'ELECTRICITY_ON_SITE_GENERATION_UNCONSUMED'), ('NG_C_S', 'NATURAL_GAS_CONSUMPTION_SUPPLIED')], max_length=3)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectBlock')),
            ],
        ),
        migrations.RemoveField(
            model_name='fueltypesummary',
            name='project_block',
        ),
        migrations.RemoveField(
            model_name='consumptionmetadata',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummaryactual',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummarybaseline',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummaryreporting',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummaryactual',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummarybaseline',
            name='fuel_type_summary',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummaryreporting',
            name='fuel_type_summary',
        ),
        migrations.AddField(
            model_name='consumptionmetadata',
            name='interpretation',
            field=models.CharField(choices=[('E_C_S', 'ELECTRICITY_CONSUMPTION_SUPPLIED'), ('E_C_T', 'ELECTRICITY_CONSUMPTION_TOTAL'), ('E_C_N', 'ELECTRICITY_CONSUMPTION_NET'), ('E_OSG_T', 'ELECTRICITY_ON_SITE_GENERATION_TOTAL'), ('E_OSG_C', 'ELECTRICITY_ON_SITE_GENERATION_CONSUMED'), ('E_OSG_U', 'ELECTRICITY_ON_SITE_GENERATION_UNCONSUMED'), ('NG_C_S', 'NATURAL_GAS_CONSUMPTION_SUPPLIED')], default='E_C_S', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumptionmetadata',
            name='label',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.DeleteModel(
            name='FuelTypeSummary',
        ),
        migrations.AddField(
            model_name='dailyusagesummaryactual',
            name='interpretation_summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datastore.InterpretationSummary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyusagesummarybaseline',
            name='interpretation_summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datastore.InterpretationSummary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyusagesummaryreporting',
            name='interpretation_summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datastore.InterpretationSummary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyusagesummaryactual',
            name='interpretation_summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datastore.InterpretationSummary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyusagesummarybaseline',
            name='interpretation_summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datastore.InterpretationSummary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyusagesummaryreporting',
            name='interpretation_summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datastore.InterpretationSummary'),
            preserve_default=False,
        ),
    ]
