# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0026_auto_20160712_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrun',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectrun',
            name='n_days',
        ),
        migrations.RemoveField(
            model_name='projectrun',
            name='start_date',
        ),
    ]
