# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0027_auto_20160712_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyusagebaseline',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='dailyusagereporting',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummaryactual',
            name='interpretation_summary',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummarybaseline',
            name='interpretation_summary',
        ),
        migrations.RemoveField(
            model_name='dailyusagesummaryreporting',
            name='interpretation_summary',
        ),
        migrations.RemoveField(
            model_name='interpretationsummary',
            name='project_block',
        ),
        migrations.RemoveField(
            model_name='monthlyaverageusagebaseline',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='monthlyaverageusagereporting',
            name='meter_run',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummaryactual',
            name='interpretation_summary',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummarybaseline',
            name='interpretation_summary',
        ),
        migrations.RemoveField(
            model_name='monthlyusagesummaryreporting',
            name='interpretation_summary',
        ),
        migrations.DeleteModel(
            name='DailyUsageBaseline',
        ),
        migrations.DeleteModel(
            name='DailyUsageReporting',
        ),
        migrations.DeleteModel(
            name='DailyUsageSummaryActual',
        ),
        migrations.DeleteModel(
            name='DailyUsageSummaryBaseline',
        ),
        migrations.DeleteModel(
            name='DailyUsageSummaryReporting',
        ),
        migrations.DeleteModel(
            name='InterpretationSummary',
        ),
        migrations.DeleteModel(
            name='MonthlyAverageUsageBaseline',
        ),
        migrations.DeleteModel(
            name='MonthlyAverageUsageReporting',
        ),
        migrations.DeleteModel(
            name='MonthlyUsageSummaryActual',
        ),
        migrations.DeleteModel(
            name='MonthlyUsageSummaryBaseline',
        ),
        migrations.DeleteModel(
            name='MonthlyUsageSummaryReporting',
        ),
    ]
