# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0027_auto_20160719_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='weather_station',
        ),
        migrations.AddField(
            model_name='projectresult',
            name='weather_normal_source_station',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='weather_source_station',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
