# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 18:06
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0029_projectresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DerivativeAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_interpretation', models.CharField(max_length=100)),
                ('interpretation', models.CharField(max_length=100)),
                ('baseline_value', models.FloatField()),
                ('baseline_upper', models.FloatField()),
                ('baseline_lower', models.FloatField()),
                ('baseline_n', models.IntegerField()),
                ('reporting_value', models.FloatField()),
                ('reporting_upper', models.FloatField()),
                ('reporting_lower', models.FloatField()),
                ('reporting_n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyTraceModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('cvrmse', models.FloatField(blank=True, null=True)),
                ('model_serializiation', models.CharField(blank=True, max_length=10000, null=True)),
                ('upper', models.FloatField(blank=True, null=True)),
                ('lower', models.FloatField(blank=True, null=True)),
                ('n', models.FloatField(blank=True, null=True)),
                ('energy_trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ConsumptionMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='ModelingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.CharField(choices=[('BASELINE', 'Baseline'), ('REPORTING', 'Reporting')], max_length=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelingPeriodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_period', to='datastore.ModelingPeriod')),
            ],
        ),
        migrations.RemoveField(
            model_name='meterrun',
            name='consumption_metadata',
        ),
        migrations.RemoveField(
            model_name='meterrun',
            name='project',
        ),
        migrations.AddField(
            model_name='projectresult',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 15, 18, 6, 8, 526110, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectresult',
            name='eemeter_version',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectresult',
            name='meter_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='meter_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 15, 18, 6, 25, 606016, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MeterRun',
        ),
        migrations.AddField(
            model_name='modelingperiodgroup',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='modelingperiodgroup',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_period', to='datastore.ModelingPeriod'),
        ),
        migrations.AddField(
            model_name='modelingperiod',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='modeling_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ModelingPeriod'),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='derivativeaggregation',
            name='modeling_period_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ModelingPeriodGroup'),
        ),
        migrations.AddField(
            model_name='derivativeaggregation',
            name='project_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectResult'),
        ),
        migrations.AddField(
            model_name='derivative',
            name='energy_trace_model_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.EnergyTraceModelResult'),
        ),
    ]
