# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0029_auto_20160727_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresult',
            name='project_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datastore.ProjectRun'),
        ),
    ]
