# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0030_projectresult_project_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytracemodelresult',
            name='traceback',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
