# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0031_energytracemodelresult_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytracemodelresult',
            name='input_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='input_n_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='input_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
