# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0032_auto_20160816_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytracemodelresult',
            name='records_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='records_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energytracemodelresult',
            name='records_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
